### ISSUE TITLE
Cannot find module meow with vbuild 6.1.0

### ISSUE THREAD

**Issue by layanto** [egoist/vbuild#105]
Tried upgrading vbuild from 5.2.0 to 6.1.0 and both vbuild --dev and vbuild failed with cannot find module meow error. Do I need to change any vbuild config from vbuild 5.x to 6.x?

```
> vbuild

module.js:471
    throw err;
    ^

Error: Cannot find module 'meow'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Projects\Baseline\client\node_modules\vbuild\bin\vbuild-pack:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by egoist** [comment]
Good call, it's missing in vbuild, you can reinstall `v6.1.1` to fix this.
