### ISSUE TITLE
vue package version mismatch

### ISSUE THREAD

**Issue by aeosynth** [egoist/vbuild#62]
vbuild 4.11, on a fresh `init`:

```
$ vbuild --dev

> draft is running at http://localhost:4000

> Mode           Hot Reloading, IIFE
> Entry[client]  src/index.js, /usr/local/lib/node_modules/vbuild/node_modules/webpack-hot-middleware/client.js?reload=true
> Output         ~/src/test/draft/dist/[name].js
> Config         ~/src/test/draft/vue.config.js
> Port           4000
> Devtool        eval-source-map

ERROR in ./src/components/App.vue
Module build failed: Error:

Vue packages version mismatch:

- vue@2.1.1
- vue-template-compiler@2.1.3

ERROR in ./src/components/App.vue
Module build failed: Error:

Vue packages version mismatch:

- vue@2.1.1
- vue-template-compiler@2.1.3

This may cause things to work incorrectly. Make sure to use the same version for
both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/usr/local/lib/node_modules/vbuild/node_modules/vue-template-compiler/index.js:8:9)
    at Module._compile (module.js:571:32)
    at Module._compile (/usr/local/lib/node_modules/vbuild/node_modules/source-map-support/source-map-support.js:471:25)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/vbuild/node_modules/vue-loader/lib/parser.js:1:16)
    at Module._compile (module.js:571:32)
    at Module._compile (/usr/local/lib/node_modules/vbuild/node_modules/source-map-support/source-map-support.js:471:25)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/vbuild/node_modules/vue-loader/lib/loader.js:3:13)
    at Module._compile (module.js:571:32)
    at Module._compile (/usr/local/lib/node_modules/vbuild/node_modules/source-map-support/source-map-support.js:471:25)
    at Object.Module._extensions..js (module.js:580:10)
 @ ./src/app.js 3:0-37
 @ ./src/index.js
 @ multi client
Child html-webpack-plugin for "index.html":

[16:33:19] Failed in 75 ms
```

**Comment by egoist** [comment]
Thanks for reporting, maybe it's because of the cache, vue should `2.1.3` too. 

I think we need to save the exact version of vue and vue-template-compiler in package.json to prevent this, will fix it soon.

**Comment by egoist** [comment]
upgrade to `vbuild^4.1.2` and the issue should be gone.
