### ISSUE TITLE
extract inline-css

### ISSUE THREAD

**Issue by throrin19** [egoist/vbuild#82]
Hi,
I have a problem with vbuild. If I import my css like this in my project : 

```javascript
import '../../src/stylesheets/style.scss';
```

The css is in the js file. It's not extract and add into the css project file. It's normal ?

This is my config : 

```javascript
const path = require('path');

module.exports = {
    title    : 'My Project',
    template : __dirname + '/docs/index.html',
    postcss  : {
        autoprefixer : {
            browsers : ['ie > 9', 'chrome > 42']
        }
    },
    entry : {
        client   : ['./docs/src/index.js']
    },
    eslint : {
        configFile : './.eslintrc.json'
    },
    mergeConfig : {
        resolve : {
            alias : {
                styles   : path.resolve(__dirname, './src/stylesheets'),
                vue$     : 'vue/dist/vue.js'
            }
        },
        module : {
            rules : [
                {
                    test    : /\.scss$/,
                    loaders : ['style-loader', 'css-loader', 'sass-loader']
                }
            ]
        }
    }
};
```

**Comment by egoist** [comment]
use [extract-text-css-plugin](https://github.com/webpack/extract-text-webpack-plugin)

if you use scss in single file component it already has extraction support.

**Comment by throrin19** [comment]
Have you an example to use it with vbuild ? After test I have an error : 

```
TypeError: Cannot read property '/home/throrin19/Development/libs/goomeo-vue/node_modules/extract-text-webpack-plugin' of null
    at /home/throrin19/Development/libs/goomeo-vue/node_modules/extract-text-webpack-plugin/index.js:257:27
    at /home/throrin19/Development/libs/goomeo-vue/node_modules/webpack/lib/Compilation.js:476:4
    at Array.forEach (native)
    at callback (/home/throrin19/Development/libs/goomeo-vue/node_modules/webpack/lib/Compilation.js:475:14)
    at Compilation.<anonymous> (/home/throrin19/Development/libs/goomeo-vue/node_modules/webpack/lib/Compilation.js:496:4)
    at /home/throrin19/Development/libs/goomeo-vue/node_modules/webpack/lib/Compilation.js:335:10
    at /home/throrin19/Development/libs/goomeo-vue/node_modules/webpack/node_modules/async/dist/async.js:356:16
```

and this is my new config : 

```javascript
const path                  = require('path');
const ExtractTextPlugin     = require('extract-text-webpack-plugin');

module.exports = {
    title    : 'My Project',
    template : __dirname + '/docs/index.html',
    postcss  : {
        autoprefixer : {
            browsers : ['ie > 9', 'chrome > 42']
        }
    },
    entry : {
        client   : ['./docs/src/index.js']
    },
    eslint : {
        configFile : './.eslintrc.json'
    },
    mergeConfig : {
        resolve : {
            alias : {
                styles   : path.resolve(__dirname, './src/stylesheets'),
                vue$     : 'vue/dist/vue.js'
            }
        },
        module : {
            rules : [
                {
                    test    : /\.scss$/,
                    loader  : ExtractTextPlugin.extract({
                        fallbackLoader  : 'style-loader',
                        loader          : ['style-loader', 'css-loader', 'sass-loader']
                    })
                }
            ]
        },
        plugins : [
            new ExtractTextPlugin("styles.css")
        ]
    }
};
```

**Comment by egoist** [comment]
um, it works for me, btw:

- you don't need to install `extract-text-webpack-plugin`, if you installe please make sure it's ^2 version
- it should be `loader  : ['css-loader', 'sass-loader']`

**Comment by throrin19** [comment]
Ok, I test with the last version : **2.0.0-beta.4** with this config : 

```javascript
mergeConfig : {
        resolve : {
            alias : {
                styles   : path.resolve(__dirname, './src/stylesheets'),
                vue$     : 'vue/dist/vue.js'
            }
        },
        module : {
            rules : [
                {
                    test    : /\.scss$/,
                    loader  : ExtractTextPlugin.extract({
                        fallbackLoader  : 'style-loader',
                        loader          : ['css-loader', 'sass-loader']
                    })
                }
            ]
        },
        plugins : [
            new ExtractTextPlugin('[name].[chunkhash].css')
        ]
}
```

And the css is already in the js file

**Comment by egoist** [comment]
I just can't reproduce 😢, your config works fine after I added a scss file to a `vbuild init` generated project.

**Comment by throrin19** [comment]
Ok it's good, If y remove the ExtractTextPlugin on my package.json and reinstall all of it, it works fine

**Comment by throrin19** [comment]
After update to the latest vbuild version, the extract-css don't works correctly
