### ISSUE TITLE
Some PostCSS plugins is not working

### ISSUE THREAD

**Issue by Grawl** [egoist/vbuild#89]
I checked it with `yarn` and `npm`, with global and local `vbuild`, and I can say that it's `vbuild` issue.

### `postcss-short` plugin is broken with `vbuild`.

It's working with `postcss-cli`, for example.

In a short: `postcss-short` is broken with `plugin is not a function` and `proc is not a function`. (See [`Grawl/jew-simulator` `vbuild`](https://github.com/Grawl/jew-simulator/tree/vbuild) branch)

<details><summary>Full log</summary>

```
> Building Jew Simulator for you

> Mode           IIFE
> Entry[client]  src/index.js
> Output         ~/Sites/jew-simulator/jew-simulator/[name].[chunkhash:8].js
> Config         ~/Sites/jew-simulator/vue.config.js
> Devtool        source-map                                                                                              19% building modules 81/92 modules 11 active ...ode_modules/async/internal/doLimit.jsTypeError: proc is not a function                                                                   
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/l 20% building modules 86/97 modules 11 active ...r/node_modules/async/internal/rest.jsTypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/li 35% building modules 212/214 modules 2 active ...rc/components/craft-button/style.sassTypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/l 35% building modules 213/214 modules 1 active ...rawl/Sites/jew-simulator/src/app.sassTypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)                   35% building modules 214/218 modules 4 active ...mponents/language-switcher/style.sassTypeError: proc is not a function                                                          
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/l 35% building modules 215/218 modules 3 active ...mponents/language-switcher/style.sassTypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/l 35% building modules 216/218 modules 2 active ...rc/components/craft-button/style.sassTypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/l 36% building modules 217/218 modules 1 active ...rawl/Sites/jew-simulator/src/app.sassTypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-0543dca4&scoped=true!./~/sass-loader?indentedSyntax!./src/components/buy-buttons/style.sass
Module build failed: TypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:253:26
 @ /usr/local/lib/~/vbuild/~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-0543dca4&scoped=true!./~/sass-loader?indentedSyntax!./src/components/buy-buttons/style.sass 4:14-255
 @ ./src/components/buy-buttons/module.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
 @ ./src/app.vue
 @ ./src/index.js
 @ multi client

ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-43986730!./~/sass-loader?indentedSyntax!./src/components/language-switcher/style.sass
Module build failed: TypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:253:26
 @ /usr/local/lib/~/vbuild/~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-43986730!./~/sass-loader?indentedSyntax!./src/components/language-switcher/style.sass 4:14-243
 @ ./src/components/language-switcher/module.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
 @ ./src/app.vue
 @ ./src/index.js
 @ multi client

ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-7788856e&scoped=true!./~/sass-loader?indentedSyntax!./src/components/craft-button/style.sass
Module build failed: TypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:253:26
 @ /usr/local/lib/~/vbuild/~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-7788856e&scoped=true!./~/sass-loader?indentedSyntax!./src/components/craft-button/style.sass 4:14-255
 @ ./src/components/craft-button/module.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
 @ ./src/app.vue
 @ ./src/index.js
 @ multi client

ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-17fea96a!./~/sass-loader?indentedSyntax!./src/app.sass
Module build failed: TypeError: proc is not a function
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
    at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
    at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
    at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:253:26
 @ /usr/local/lib/~/vbuild/~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-17fea96a!./~/sass-loader?indentedSyntax!./src/app.sass 4:14-223
 @ ./src/app.vue
 @ ./src/index.js
 @ multi client

ERROR in /usr/local/lib/~/vbuild/~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-0543dca4&scoped=true!./~/sass-loader?indentedSyntax!./src/components/buy-buttons/style.sass
Module build failed: Error
    at /usr/local/lib/node_modules/vbuild/node_modules/webpack/lib/NormalModule.js:143:35
    at /usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/vue-loader/lib/style-rewriter.js:103:7

ERROR in /usr/local/lib/node_modules/vbuild/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/grawl/Sites/jew-simulator/node_modules/vue-style-loader/index.js!/Users/grawl/Sites/jew-simulator/node_modules/css-loader/index.js?sourceMap&-autoprefixer!/Users/grawl/Sites/jew-simulator/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-0543dca4&scoped=true!/Users/grawl/Sites/jew-simulator/node_modules/sass-loader/index.js?indentedSyntax!/Users/grawl/Sites/jew-simulator/src/components/buy-buttons/style.sass doesn't export content

ERROR in /usr/local/lib/~/vbuild/~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-43986730!./~/sass-loader?indentedSyntax!./src/components/language-switcher/style.sass
Module build failed: Error
    at /usr/local/lib/node_modules/vbuild/node_modules/webpack/lib/NormalModule.js:143:35
    at /usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/vue-loader/lib/style-rewriter.js:103:7

ERROR in /usr/local/lib/node_modules/vbuild/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/grawl/Sites/jew-simulator/node_modules/vue-style-loader/index.js!/Users/grawl/Sites/jew-simulator/node_modules/css-loader/index.js?sourceMap&-autoprefixer!/Users/grawl/Sites/jew-simulator/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-43986730!/Users/grawl/Sites/jew-simulator/node_modules/sass-loader/index.js?indentedSyntax!/Users/grawl/Sites/jew-simulator/src/components/language-switcher/style.sass doesn't export content

ERROR in /usr/local/lib/~/vbuild/~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-7788856e&scoped=true!./~/sass-loader?indentedSyntax!./src/components/craft-button/style.sass
Module build failed: Error
    at /usr/local/lib/node_modules/vbuild/node_modules/webpack/lib/NormalModule.js:143:35
    at /usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/vue-loader/lib/style-rewriter.js:103:7

ERROR in /usr/local/lib/node_modules/vbuild/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/grawl/Sites/jew-simulator/node_modules/vue-style-loader/index.js!/Users/grawl/Sites/jew-simulator/node_modules/css-loader/index.js?sourceMap&-autoprefixer!/Users/grawl/Sites/jew-simulator/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-7788856e&scoped=true!/Users/grawl/Sites/jew-simulator/node_modules/sass-loader/index.js?indentedSyntax!/Users/grawl/Sites/jew-simulator/src/components/craft-button/style.sass doesn't export content

ERROR in /usr/local/lib/~/vbuild/~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-17fea96a!./~/sass-loader?indentedSyntax!./src/app.sass
Module build failed: Error
    at /usr/local/lib/node_modules/vbuild/node_modules/webpack/lib/NormalModule.js:143:35
    at /usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:359:11
    at /usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:225:18
    at context.callback (/usr/local/lib/node_modules/vbuild/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
    at /Users/grawl/Sites/jew-simulator/node_modules/vue-loader/lib/style-rewriter.js:103:7

ERROR in /usr/local/lib/node_modules/vbuild/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/Users/grawl/Sites/jew-simulator/node_modules/vue-style-loader/index.js!/Users/grawl/Sites/jew-simulator/node_modules/css-loader/index.js?sourceMap&-autoprefixer!/Users/grawl/Sites/jew-simulator/node_modules/vue-loader/lib/style-rewriter.js?id=data-v-17fea96a!/Users/grawl/Sites/jew-simulator/node_modules/sass-loader/index.js?indentedSyntax!/Users/grawl/Sites/jew-simulator/src/app.sass doesn't export content
Child html-webpack-plugin for "index.html":
    
Child extract-text-webpack-plugin:
    
    ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-0543dca4&scoped=true!./~/sass-loader?indentedSyntax!./src/components/buy-buttons/style.sass
    Module build failed: TypeError: proc is not a function
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
        at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
        at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
        at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:253:26
Child extract-text-webpack-plugin:
    
    ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-43986730!./~/sass-loader?indentedSyntax!./src/components/language-switcher/style.sass
    Module build failed: TypeError: proc is not a function
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
        at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
        at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
        at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:253:26
Child extract-text-webpack-plugin:
    
    ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-7788856e&scoped=true!./~/sass-loader?indentedSyntax!./src/components/craft-button/style.sass
    Module build failed: TypeError: proc is not a function
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
        at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
        at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
        at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:253:26
Child extract-text-webpack-plugin:
    
    ERROR in ./~/css-loader?sourceMap&-autoprefixer!./~/vue-loader/lib/style-rewriter.js?id=data-v-17fea96a!./~/sass-loader?indentedSyntax!./src/app.sass
    Module build failed: TypeError: proc is not a function
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:83:29
        at wrappedPlugin (/Users/grawl/Sites/jew-simulator/node_modules/postcss-devtools/dist/index.js:81:24)
        at LazyResult.run (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:321:20)
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:248:32
        at LazyResult.asyncTick (/Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:246:13)
        at /Users/grawl/Sites/jew-simulator/node_modules/postcss/lib/lazy-result.es6:253:26

[11:21:02] Failed in 22.179 s
```

</details>

With [`vuejs-templates/webpack`](https://github.com/vuejs-templates/webpack), it works. (See [`Grawl/jew-simulator`](https://github.com/Grawl/jew-simulator) master branch)

**Comment by egoist** [comment]
use the postcss api directly then:

```js
module.exports = {
  postcss() {
    return [] // plugins
  }
}
```

**Comment by Grawl** [comment]
Thank you, now it's worked.

```js
import postcssDevtools from 'postcss-devtools'
import postcssPositionAlt from 'postcss-position-alt'
import postcssShort from 'postcss-short'
import postcssAxis from 'postcss-axis'
module.exports = {
	title: 'Jew Simulator',
	…
	resolve: true,
	postcss() {
		return [
			postcssDevtools,
			postcssPositionAlt,
			postcssShort,
			postcssAxis,
		]
	},
}
```

But where is the problem? `postcss-short` or `vbuild`?

**Comment by egoist** [comment]
I'm not sure, but it looks is broken by postcss-devtools?

**Comment by Grawl** [comment]
No. I tried to load only `postcss-short` and it was broken.

**Comment by egoist** [comment]
ok,  now I'm closing this.

**Comment by Grawl** [comment]
Are you sure the problem is not in `vbuild`? With `postcss-cli` it works.

**Comment by egoist** [comment]
https://github.com/egoist/vbuild/blob/master/lib/update-config.js#L139-L163 this is the code we use to apply postcss plugins

**Comment by Grawl** [comment]
Looks ok. I think we need @ai here.

**Comment by egoist** [comment]
no matter what, that way of updating postcss plugins will be deprecated later https://github.com/egoist/vbuild/issues/75 😅

**Comment by Grawl** [comment]
I ltke that. Native way is the best way always.
