### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by layanto** [egoist/vbuild#96]
npm run dev works fine (not sure whether this means no code error) but npm run build raises error:
```
14 verbose stack Error: baseline-client@ build: `vbuild`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid baseline-client@
16 verbose cwd C:\Projects\Baseline\client
```
Console shows (last few lines before error):
```
WARNING in asset size limit: The following asset(s) exceed the recommended size
limit (250 kB).
This can impact web performance.
Assets:
  static/materialdesignicons-webfont.svg (1.86 MB)
  vendor.26710373.js (412 kB)
  vendor.7c29af1b.css (259 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  client (707 kB)
      manifest.fdaeea09.js
      vendor.26710373.js
      vendor.7c29af1b.css
      client.a564545d.js
      client.5ca095ff.css

  vendor (673 kB)
      manifest.fdaeea09.js
      vendor.26710373.js
      vendor.7c29af1b.css


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child html-webpack-plugin for "index.html":

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

Child extract-text-webpack-plugin:

[08:03:17] Failed in 19.124 s
```

npm run build used to work but I haven't tried building for production in a while. I will try with older version of vbuild and also with older code base to try and narrow down where the problem is. But appreciate your input.

**Comment by layanto** [comment]
Maybe to do with npm warning I get:
```
npm WARN extract-text-webpack-plugin@2.0.0-beta.4 requires a peer of webpack@^2.1.0-beta.19 but none was installed.
```

**Comment by layanto** [comment]
Reverting to vbuild v4.4.0, without changing any code, npm run build runs without error

**Comment by egoist** [comment]
disable it with

```js
module.exports = {
  mergeConfig: {
    performance: {hints: false}
  }
}
```

**Comment by layanto** [comment]
That works. Thank you.
But if it is just a hint, then it really should fail the build.
