### ISSUE TITLE
Build fails out of box

### ISSUE THREAD

**Issue by dodas** [egoist/vbuild#98]
Hello,
I just ran `vbuild init v`, `cd v`, `yarn`, `yarn build` and following error occured:
```
ERROR in ./src/components/App.vue      e Module build failed: TypeError: loader.charAt is not a function
    at ensureBang (/Users/jozefmikulas/dev/v/node_modules/vue-loader/lib/loader.js:180:16)
    at getLoaderString (/Users/jozefmikulas/dev/v/node_modules/vue-loader/lib/loader.js:145:18)
    at getRequireString (/Users/jozefmikulas/dev/v/node_modules/vue-loader/lib/loader.js:80:7)
    at getRequire (/Users/jozefmikulas/dev/v/node_modules/vue-loader/lib/loader.js:71:7)
    at /Users/jozefmikulas/dev/v/node_modules/vue-loader/lib/loader.js:205:11
    at Array.forEach (native)
    at Object.module.exports (/Users/jozefmikulas/dev/v/node_modules/vue-loader/lib/loader.js:198:18)
 @ ./src/app.js 3:0-37
 @ ./src/index.js
 @ multi client
```

What could be wrong? Sreenshot of terminal attached
<img width="962" alt="vbuild webpack error" src="https://cloud.githubusercontent.com/assets/14360171/22384995/20138c1a-e4d1-11e6-89a3-b22cb9c5eebc.png">

**Comment by egoist** [comment]
maybe try upgrading vue-loader

**Comment by RyanZim** [comment]
Having the same issue, vue-loader v10.0.2.

**Comment by dodas** [comment]
Everything is up to date, as I just installed all dependencies. Output of `yarn upgrade`:
```
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning Unmet peer dependency "css-loader@*".
warning Incorrect peer dependency "vue@^2.1.6".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 312 new dependencies.
├─ abbrev@1.0.9
├─ acorn-jsx@3.0.1
├─ acorn@4.0.4
├─ ajv-keywords@1.5.1
├─ ajv@4.11.2
├─ ansi-align@1.1.0
├─ ansi-escapes@1.4.0
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ argparse@1.0.9
├─ array-differ@1.0.0
├─ array-find-index@1.0.2
├─ array-union@1.0.2
├─ array-uniq@1.0.3
├─ array-unique@0.2.1
├─ arrify@1.0.1
├─ async-validator@1.6.8
├─ babel-code-frame@6.22.0
├─ babel-helper-vue-jsx-merge-props@2.0.2
├─ balanced-match@0.4.2
├─ big.js@3.1.3
├─ bluebird@3.4.7
├─ boxen@0.6.0
├─ brace-expansion@1.1.6
├─ buf-compare@1.0.1
├─ buffer-shims@1.0.0
├─ builtin-modules@1.1.1
├─ caller-path@0.1.0
├─ callsites@0.2.0
├─ camelcase-keys@2.1.0
├─ camelcase@2.1.1
├─ capture-stack-trace@1.0.0
├─ chalk@1.1.3
├─ circular-json@0.3.1
├─ cli-boxes@1.0.0
├─ cli-cursor@1.0.2
├─ cli-width@2.1.0
├─ co@4.6.0
├─ code-point-at@1.1.0
├─ commander@2.9.0
├─ concat-map@0.0.1
├─ concat-stream@1.6.0
├─ config-chain@1.1.11
├─ configstore@2.1.0
├─ consolidate@0.14.5
├─ contains-path@0.1.0
├─ core-assert@0.2.1
├─ core-js@2.4.1
├─ core-util-is@1.0.2
├─ create-error-class@3.0.2
├─ cross-spawn@4.0.2
├─ currently-unhandled@0.4.1
├─ d@0.1.1
├─ de-indent@1.0.2
├─ debug@2.6.0
├─ decamelize@1.2.0
├─ deep-assign@1.0.0
├─ deep-extend@0.4.1
├─ deep-is@0.1.3
├─ deep-strict-equal@0.2.0
├─ deepmerge@1.3.2
├─ del@2.2.2
├─ doctrine@1.5.0
├─ dot-prop@3.0.0
├─ duplexer2@0.1.4
├─ editorconfig@0.13.2
├─ element-ui@1.1.6
├─ emojis-list@2.1.0
├─ enhance-visitors@1.0.0
├─ error-ex@1.3.0
├─ es5-ext@0.10.12
├─ es6-iterator@2.0.0
├─ es6-map@0.1.4
├─ es6-set@0.1.4
├─ es6-symbol@3.1.0
├─ es6-weak-map@2.0.1
├─ escape-string-regexp@1.0.5
├─ escope@3.6.0
├─ eslint-config-xo@0.17.0
├─ eslint-formatter-pretty@1.1.0
├─ eslint-import-resolver-node@0.2.3
├─ eslint-module-utils@2.0.0
├─ eslint-plugin-ava@3.1.1
├─ eslint-plugin-import@2.2.0
├─ eslint-plugin-no-use-extend-native@0.3.12
├─ eslint-plugin-promise@3.4.0
├─ eslint-plugin-unicorn@1.0.0
├─ eslint@3.14.1
├─ espree@3.3.2
├─ esprima@2.7.3
├─ espurify@1.6.0
├─ esrecurse@4.1.0
├─ estraverse@4.2.0
├─ esutils@2.0.2
├─ event-emitter@0.3.4
├─ execa@0.5.1
├─ exit-hook@1.1.1
├─ fast-levenshtein@2.0.6
├─ figures@1.7.0
├─ file-entry-cache@2.0.0
├─ filled-array@1.1.0
├─ find-up@2.1.0
├─ flat-cache@1.2.2
├─ flatten@1.0.2
├─ fs.realpath@1.0.0
├─ function-bind@1.1.0
├─ generate-function@2.0.0
├─ generate-object-property@1.2.0
├─ get-set-props@0.1.0
├─ get-stdin@5.0.1
├─ get-stream@2.3.1
├─ glob@7.1.1
├─ globals@9.14.0
├─ globby@6.1.0
├─ got@5.7.1
├─ graceful-fs@4.1.11
├─ graceful-readlink@1.0.1
├─ has-ansi@2.0.0
├─ has-flag@2.0.0
├─ has@1.0.1
├─ hash-sum@1.0.2
├─ he@1.1.1
├─ hosted-git-info@2.1.5
├─ ignore@3.2.2
├─ imurmurhash@0.1.4
├─ indent-string@2.1.0
├─ indexes-of@1.0.1
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ ini@1.3.4
├─ inquirer@0.12.0
├─ interpret@1.0.1
├─ irregular-plurals@1.2.0
├─ is-arrayish@0.2.1
├─ is-builtin-module@1.0.0
├─ is-error@2.2.1
├─ is-extglob@1.0.0
├─ is-finite@1.0.2
├─ is-fullwidth-code-point@2.0.0
├─ is-get-set-prop@1.0.0
├─ is-glob@2.0.1
├─ is-js-type@2.0.0
├─ is-my-json-valid@2.15.0
├─ is-npm@1.0.0
├─ is-obj-prop@1.0.0
├─ is-obj@1.0.1
├─ is-path-cwd@1.0.0
├─ is-path-in-cwd@1.0.0
├─ is-path-inside@1.0.0
├─ is-plain-obj@1.1.0
├─ is-property@1.0.2
├─ is-proto-prop@1.0.0
├─ is-redirect@1.0.0
├─ is-resolvable@1.0.0
├─ is-retry-allowed@1.1.0
├─ is-stream@1.1.0
├─ is-utf8@0.2.1
├─ isarray@1.0.0
├─ isexe@1.1.2
├─ js-base64@2.1.9
├─ js-beautify@1.6.8
├─ js-tokens@3.0.0
├─ js-types@1.0.0
├─ js-yaml@3.7.0
├─ json-stable-stringify@1.0.1
├─ json5@0.5.1
├─ jsonify@0.0.0
├─ jsonpointer@4.0.1
├─ latest-version@2.0.0
├─ lazy-req@1.1.0
├─ levn@0.3.0
├─ load-json-file@2.0.0
├─ loader-utils@0.2.16
├─ locate-path@2.0.0
├─ lodash.camelcase@4.3.0
├─ lodash.cond@4.5.2
├─ lodash.kebabcase@4.1.1
├─ lodash.snakecase@4.1.1
├─ lodash.upperfirst@4.3.1
├─ lodash@4.17.4
├─ log-symbols@1.0.2
├─ loud-rejection@1.6.0
├─ lowercase-keys@1.0.0
├─ lru-cache@4.0.2
├─ map-obj@1.0.1
├─ meow@3.7.0
├─ minimatch@3.0.3
├─ minimist@1.2.0
├─ mkdirp@0.5.1
├─ ms@0.7.2
├─ multimatch@2.1.0
├─ mute-stream@0.0.5
├─ natural-compare@1.4.0
├─ node-status-codes@1.0.0
├─ nopt@3.0.6
├─ normalize-package-data@2.3.5
├─ npm-run-path@2.0.2
├─ number-is-nan@1.0.1
├─ obj-props@1.1.0
├─ object-assign@4.1.1
├─ once@1.4.0
├─ onetime@1.1.0
├─ optionator@0.8.2
├─ os-homedir@1.0.2
├─ os-tmpdir@1.0.2
├─ osenv@0.1.4
├─ p-finally@1.0.0
├─ p-limit@1.1.0
├─ p-locate@2.0.0
├─ package-json@2.4.0
├─ parse-gitignore@0.3.1
├─ parse-json@2.2.0
├─ path-exists@3.0.0
├─ path-is-absolute@1.0.1
├─ path-is-inside@1.0.2
├─ path-key@2.0.1
├─ path-type@1.1.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ pkg-conf@2.0.0
├─ pkg-dir@1.0.0
├─ pkg-up@1.0.0
├─ plur@2.1.2
├─ pluralize@1.2.1
├─ postcss-selector-parser@2.2.2
├─ postcss@5.2.11
├─ prelude-ls@1.1.2
├─ prepend-http@1.0.4
├─ process-nextick-args@1.0.7
├─ progress@1.1.8
├─ proto-list@1.2.4
├─ proto-props@0.2.1
├─ pseudomap@1.0.2
├─ rc@1.1.6
├─ read-all-stream@3.1.0
├─ read-pkg-up@1.0.1
├─ read-pkg@1.1.0
├─ readable-stream@2.2.2
├─ readline2@1.0.1
├─ rechoir@0.6.2
├─ redent@1.0.0
├─ registry-auth-token@3.1.0
├─ registry-url@3.1.0
├─ repeating@2.0.1
├─ req-all@0.1.0
├─ require-uncached@1.0.3
├─ resolve-cwd@1.0.0
├─ resolve-from@2.0.0
├─ resolve@1.2.0
├─ restore-cursor@1.0.1
├─ rimraf@2.5.4
├─ run-async@0.1.0
├─ rx-lite@3.1.2
├─ semver-diff@2.1.0
├─ semver@5.3.0
├─ shelljs@0.7.6
├─ sigmund@1.0.1
├─ signal-exit@3.0.2
├─ slice-ansi@0.0.4
├─ slide@1.1.6
├─ sort-keys@1.1.2
├─ source-map@0.5.6
├─ spdx-correct@1.0.2
├─ spdx-expression-parse@1.0.4
├─ spdx-license-ids@1.2.2
├─ sprintf-js@1.0.3
├─ string_decoder@0.10.31
├─ string-width@2.0.0
├─ strip-ansi@3.0.1
├─ strip-bom@3.0.0
├─ strip-eof@1.0.0
├─ strip-indent@1.0.1
├─ strip-json-comments@2.0.1
├─ supports-color@3.2.3
├─ table@3.8.3
├─ text-table@0.2.0
├─ the-argv@1.0.0
├─ throttle-debounce@1.0.1
├─ through@2.3.8
├─ timed-out@3.1.3
├─ trim-newlines@1.0.0
├─ tryit@1.0.3
├─ type-check@0.3.2
├─ typedarray@0.0.6
├─ uniq@1.0.1
├─ unzip-response@1.0.2
├─ update-notifier@1.0.3
├─ url-parse-lax@1.0.0
├─ user-home@2.0.0
├─ util-deprecate@1.0.2
├─ uuid@2.0.3
├─ validate-npm-package-license@3.0.1
├─ vue-hot-reload-api@2.0.8
├─ vue-loader@10.0.2
├─ vue-style-loader@1.0.0
├─ vue-template-compiler@2.1.5
├─ vue-template-es2015-compiler@1.5.0
├─ vue@2.1.5
├─ which@1.2.12
├─ widest-line@1.0.0
├─ wordwrap@1.0.0
├─ wrappy@1.0.2
├─ write-file-atomic@1.3.1
├─ write-json-file@2.0.0
├─ write-pkg@2.0.0
├─ write@0.2.1
├─ xdg-basedir@2.0.0
├─ xo-init@0.4.0
├─ xo@0.17.1
├─ xtend@4.0.1
└─ yallist@2.0.0
✨  Done in 6.36s.
```

**Comment by egoist** [comment]
I mean try vue-loader 10.1.2

**Comment by RyanZim** [comment]
Will try ASAP.

**Comment by RyanZim** [comment]
vue-loader@10.1.2 works fine!

One question: vue-loader requires a peer of css-loader; shouldn't css-loader be included in the package.json generated by `vbuild init`?

**Comment by egoist** [comment]
@RyanZim it's a dep of vbuild so you don't need to install it again

**Comment by RyanZim** [comment]
OK gotcha, npm was complaining because I was using a global version of vbuild.

**Comment by boustanihani** [comment]
**I can confirm that vbuild is failing out of box!**

After calling `yarn` I get =>

`warning "vue-loader@10.0.2" has unmet peer dependency "css-loader@*".`

When I call `yarn dev` I get =>
```
ERROR  Failed to compile with 3 errors

These dependencies were not found in node_modules:

* ./src/index.js
* ansi-html
* html-entities

Did you forget to run npm install --save for them?
```

And the browser output is =>

```
Html Webpack Plugin:
  Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'html-webpack-plugin/lib/loader.js' in '/home/ubuntu/workspace/000/vue-vbu  ild':
  Error: Can't resolve 'html-webpack-plugin/lib/loader.js' in '/home/ubuntu/workspace/000/vue-vbuild'
  
  - compiler.js:76 
    [workspace]/[html-webpack-plugin]/lib/compiler.js:76:16
  
  - Compiler.js:282 Compiler.
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:282:10
  
  - Compiler.js:479 
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:479:13
  
  - Tapable.js:138 next
    [workspace]/[tapable]/lib/Tapable.js:138:11
  
  - CachePlugin.js:61 Compiler.
    [workspace]/[vbuild]/[webpack]/lib/CachePlugin.js:61:4
  
  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [workspace]/[tapable]/lib/Tapable.js:142:13
  
  - Compiler.js:476 
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:476:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [workspace]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:625 
    [workspace]/[vbuild]/[webpack]/lib/Compilation.js:625:18
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [workspace]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:616 
    [workspace]/[vbuild]/[webpack]/lib/Compilation.js:616:10
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [workspace]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:611 
    [workspace]/[vbuild]/[webpack]/lib/Compilation.js:611:9
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [workspace]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:607 sealPart2
    [workspace]/[vbuild]/[webpack]/lib/Compilation.js:607:8
  
  - Tapable.js:131 Compilation.applyPluginsAsyncSeries
    [workspace]/[tapable]/lib/Tapable.js:131:46
  
  - Compilation.js:553 Compilation.seal
    [workspace]/[vbuild]/[webpack]/lib/Compilation.js:553:7
  
  - Compiler.js:473 
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:473:16
  
  - Tapable.js:225 
    [workspace]/[tapable]/lib/Tapable.js:225:11
  
  - Compilation.js:454 Compilation.
    [workspace]/[vbuild]/[webpack]/lib/Compilation.js:454:10
  
  - Compilation.js:349 Compilation.errorAndCallback
    [workspace]/[vbuild]/[webpack]/lib/Compilation.js:349:3
  
  - Compilation.js:366 Compilation.
    [workspace]/[vbuild]/[webpack]/lib/Compilation.js:366:11
  
  - From previous event:
  
  - compiler.js:69 Object.compileTemplate
    [workspace]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.
    [workspace]/[html-webpack-plugin]/index.js:47:40
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [workspace]/[tapable]/lib/Tapable.js:229:14
  
  - Compiler.js:468 
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:468:8
  
  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [workspace]/[tapable]/lib/Tapable.js:131:46
  
  - Compiler.js:461 Compiler.compile
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:461:7
  
  - Compiler.js:47 
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:47:17
  
  - Tapable.js:138 next
    [workspace]/[tapable]/lib/Tapable.js:138:11
  
  - Shared.js:138 Compiler.compilerInvalid
    [workspace]/[webpack-dev-middleware]/lib/Shared.js:138:5
  
  - Tapable.js:140 next
    [workspace]/[tapable]/lib/Tapable.js:140:14
  
  - CachePlugin.js:31 Compiler.
    [workspace]/[vbuild]/[webpack]/lib/CachePlugin.js:31:4
  
  - Tapable.js:142 Compiler.applyPluginsAsyncSeries
    [workspace]/[tapable]/lib/Tapable.js:142:13
  
  - Compiler.js:45 Watching._go
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:45:16
  
  - Compiler.js:36 Watching.
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:36:8
  
  - Compiler.js:371 Compiler.readRecords
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:371:10
  
  - Compiler.js:33 new Watching
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:33:16
  
  - Compiler.js:205 Compiler.watch
    [workspace]/[vbuild]/[webpack]/lib/Compiler.js:205:17
  
  - Shared.js:153 Object.startWatch
    [workspace]/[webpack-dev-middleware]/lib/Shared.js:153:29
  
  - Shared.js:215 Shared
    [workspace]/[webpack-dev-middleware]/lib/Shared.js:215:8
  
  - middleware.js:22 module.exports
    [workspace]/[webpack-dev-middleware]/middleware.js:22:15
  
  - server.js:14 module.exports
    [workspace]/[vbuild]/lib/server.js:14:58
  
  - dev.js:6 module.exports
    [workspace]/[vbuild]/lib/dev.js:6:3
  
  - index.js:84 
    [workspace]/[vbuild]/lib/index.js:84:21
  
  - Generator.next
  
  - index.js:65 onFulfilled
    [workspace]/[vbuild]/[co]/index.js:65:19
```
